project:
  type: website
  output-dir: docs
  resources:
    - assets/files/cv/Sam_Hall-McMaster_CV.pdf

website:
  title: ""
  search: false
  navbar:
    left:
      - href: home.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

home: home.qmd