---
title: "Publications"
---

# Preprints
- **Hall-McMaster, S.**, Tomov, M., \*Gershman, S.J, & \*Schuck, N.W. Neural prioritisation of past solutions supports generalisation. \*equal contribution. [[preprint]](https://www.biorxiv.org/content/10.1101/2024.06.10.598294v2) [[data + code]](https://gin.g-node.org/sam.hall-mcmaster)

- Hedrich, N.L., Schulz, E., **\*Hall-McMaster, S.**, & \*Schuck, N.W. Reinforcement learning is biased towards slowly changing features. *equal contribution. [[preprint]](https://www.biorxiv.org/content/10.1101/2024.01.24.576910v1)

- Radzikowska, M., Pike, A. C., & **Hall-McMaster, S.** Computational perspectives on behaviour in anorexia nervosa: A systematic review. [[preprint]](https://osf.io/preprints/psyarxiv/wq4cz)

# Published Papers
- **Hall-McMaster, S.**, Stokes, M.G., & Myers, N.E. (2022). Integrating reward information for prospective behaviour. *Journal of Neuroscience*, 42(9), 1804-1819. [[paper]](https://www.jneurosci.org/content/42/9/1804) [[data + code]](https://osf.io/vwd3k/)

- Pike, A. C., Atherton, K. E., Bauer, Y., Crittenden, B. M., van Ede, F., **Hall-McMaster, S.**, ... & Noonan, M. P. (2022). 10 simple rules for a supportive lab environment. *Journal of Cognitive Neuroscience*, 35(1), 44-48. [[paper]](https://direct.mit.edu/jocn/article/35/1/44/113591/10-Simple-Rules-for-a-Supportive-Lab-Environment)

- **Hall-McMaster, S.**, Dayan, P., & Schuck N.W. (2021). Control over patch encounters changes foraging behaviour. *iScience, 24(9)*, 1-10. [[paper]](https://www.cell.com/iscience/fulltext/S2589-0042(21)00973-1) [[data + code]](https://osf.io/c4trj/)

- Wittkuhn, L., Chien, S., **Hall-McMaster, S.**, & Schuck, N.W. (2021). Replay in minds and machines. *Neuroscience & Biobehavioral Reviews*, 129, 367-388. [[paper]](https://www.sciencedirect.com/science/article/abs/pii/S0149763421003444)

- **Hall-McMaster, S.**, Muhle-Karbe, P.S., \*Myers, N.E., & \*Stokes, M.G. (2019). Reward boosts neural coding of task rules to optimise cognitive flexibility. *Journal of Neuroscience*, 39(43), 8549-8561. \*equal contribution. [[paper]](https://www.jneurosci.org/content/39/43/8549.full) [[data + code]](https://osf.io/kuzye/)

- **Hall-McMaster, S.**, & Luyckx, F. (2019). Revisiting foraging approaches in neuroscience. *Cognitive, Affective, & Behavioral Neuroscience*, 19(2), 225-230. [[paper]](https://link.springer.com/article/10.3758/s13415-018-00682-z)

- **Hall-McMaster, S.**, Millar, J., Ruan, M., & Ward, R. D. (2017). Medial orbitofrontal cortex modulates associative learning between environmental cues and reward probability. *Behavioral Neuroscience*, 131(1), 1-10. [[paper]](https://psycnet.apa.org/buy/2016-61122-001) [[supplement](docs/publications/Hall-McMaster_etal_BNeuro_2017_SI.docx)]

- **Hall-McMaster, S. M.**, Treharne, G. J., & Smith, C. M. (2016). Positive thinking and physical activity motivation: A qualitative case study. *New Zealand Journal of Physiotherapy*, 44(1), 26-32. [[paper]](https://nzjp.org.nz/nzjp/article/view/126)

- **Hall-McMaster, S. M.**, Treharne, G. J., & Smith, C. M (2016). “The positive feel’: Unpacking the role of positive thinking in people with multiple sclerosis’s thinking aloud about staying physically active. *Journal of Health Psychology*, 21(12), 3026-3036. [[paper]](https://journals.sagepub.com/doi/abs/10.1177/1359105315592047?casa_token=ajH7SEZSJVUAAAAA%3AmDrKKQbSaapHgf-ruPCIVGIWmA2Yw4OgwS0lTYYyX172VNlSO_pcF_n7cRqlJbDFwATHap9WGDf7g7dz&journalCode=hpqa)

