---
title: "Sam Hall-McMaster"
---

# Preprints
- **Hall-McMaster, S.**, Wittkuhn, W., Verra, L., Hedrich, H.L., Irie, K., Dayan, P., \*Gershman, S.J., & \*Schuck, N.W. Entorhinal cortex signals dimensions of past experience that can be generalised in a novel environment. \*joint senior authors. [[preprint]](https://www.biorxiv.org/content/10.1101/2025.08.01.668096v1)

- Carvalho, W., **Hall-McMaster, S.**, Lee, H., Gershman, S.J. Preemptive solving of future problems: Multitask preplay in humans and machines. [[preprint]](https://arxiv.org/abs/2507.05561)

# Published Papers
- \***Hall-McMaster, S.**, & \*Zika, O. (in press) Increasing response vigour under time pressure as a transdiagnostic marker of eating disorders. *Computational Psychiatry*. *equal contribution. [[preprint]](https://osf.io/preprints/psyarxiv/kzwda?view_only=) [[data + code]](https://github.com/ozika/ed-foraging-hall-mcmaster-and-zika)

- Chau, J.M. Ison, M.J., Muhle-Karbe, P.S., Stokes, M.G., \*Myers, N.E., & \***Hall-McMaster, S.** (2025). Alpha and beta oscillations mediate the effect of motivation on neural coding of cognitive flexibility. *Biological Psychology*, 200, 109085. \*joint senior authors. [[paper]](assets/files/publications/Delgado_etal_BP_2025.pdf) [[data + code]](https://github.com/JuanMChau/AlphaBetaOscillations)

- **Hall-McMaster, S.**, Tomov, M., \*Gershman, S.J., & \*Schuck, N.W. (2025). Neural evidence that humans reuse strategies to solve new tasks. *PLOS Biology*, 23(6), e3003174. \*joint senior authors. [[paper]](assets/files/publications/Hall-McMaster_etal_PB_2025.pdf) [[supplement]](assets/files/publications/Hall-McMaster_etal_PB_2025_SI.docx) [[data + code]](https://gin.g-node.org/sam.hall-mcmaster)

- Radzikowska, M., Pike, A.C., & **Hall-McMaster, S.** (2025). Computational perspectives on cognition in anorexia nervosa: A systematic review. *Computational Psychiatry*, 9(1), 100-121. [[paper]](assets/files/publications/Radzikowska_etal_CP_2025.pdf) 

- Hedrich, N.L., Schulz, E., \*Schuck, N.W., & \***Hall-McMaster, S.** (2024). An inductive bias for slowly changing features in human reinforcement learning. *PLOS Computational Biology*, 20(11), 1-30. \*joint senior authors. [[paper]](assets/files/publications/Hedrich_etal_PCB_2024.pdf) [[data + code]](https://github.com/noahedrich/slow_prior/tree/main)

- **Hall-McMaster, S.**, Stokes, M.G., & Myers, N.E. (2022). Integrating reward information for prospective behaviour. *Journal of Neuroscience*, 42(9), 1804-1819. [[paper]](assets/files/publications/Hall-McMaster_etal_JNeuro_2022.pdf) [[data + code]](https://osf.io/vwd3k/)

- Pike, A. C., Atherton, K. E., Bauer, Y., Crittenden, B. M., van Ede, F., **Hall-McMaster, S.**, ... & Noonan, M. P. (2022). 10 simple rules for a supportive lab environment. *Journal of Cognitive Neuroscience*, 35(1), 44-48. [[paper]](assets/files/publications/Pike_etal_JCogNeuro_2022.pdf)

- **Hall-McMaster, S.**, Dayan, P., & Schuck N.W. (2021). Control over patch encounters changes foraging behaviour. *iScience, 24(9)*, 1-10. [[paper]](assets/files/publications/Hall-McMaster_etal_iScience_2021.pdf) [[data + code]](https://osf.io/c4trj/)

- Wittkuhn, L., Chien, S., **Hall-McMaster, S.**, & Schuck, N.W. (2021). Replay in minds and machines. *Neuroscience & Biobehavioral Reviews*, 129, 367-388. [[paper]](assets/files/publications/Wittkuhn_etal_NBBR_2021.pdf)

- **Hall-McMaster, S.**, Muhle-Karbe, P.S., \*Myers, N.E., & \*Stokes, M.G. (2019). Reward boosts neural coding of task rules to optimise cognitive flexibility. *Journal of Neuroscience*, 39(43), 8549-8561. \*joint senior authors. [[paper]](assets/files/publications/Hall-McMaster_etal_JNeuro_2019.pdf) [[data + code]](https://osf.io/kuzye/)

- **Hall-McMaster, S.**, & Luyckx, F. (2019). Revisiting foraging approaches in neuroscience. *Cognitive, Affective, & Behavioral Neuroscience*, 19(2), 225-230. [[paper]](assets/files/publications/Hall-McMaster_Luyckx_CABN_2019.pdf)

- **Hall-McMaster, S.**, Millar, J., Ruan, M., & Ward, R.D. (2017). Medial orbitofrontal cortex modulates associative learning between environmental cues and reward probability. *Behavioral Neuroscience*, 131(1), 1-10. [[paper]](assets/files/publications/Hall-McMaster_etal_BNeuro_2017.pdf) [[supplement](assets/files/publications/Hall-McMaster_etal_BNeuro_2017_SI.docx)]

- **Hall-McMaster, S.M.**, Treharne, G.J., & Smith, C.M. (2016). Positive thinking and physical activity motivation: A qualitative case study. *New Zealand Journal of Physiotherapy*, 44(1), 26-32. [[paper]](assets/files/publications/Hall-McMaster_etal_NZJP_2016.pdf)

- **Hall-McMaster, S.M.**, Treharne, G.J., & Smith, C.M. (2016). “The positive feel’: Unpacking the role of positive thinking in people with multiple sclerosis’s thinking aloud about staying physically active. *Journal of Health Psychology*, 21(12), 3026-3036. [[paper]](assets/files/publications/Hall-McMaster_etal_JHP_2016.pdf)

